# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('bid', models.PositiveIntegerField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
