# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abids', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='bid',
        ),
    ]
